### ISSUE TITLE
iCub speak in chinese

### ISSUE THREAD

**Issue by linzdg** [robotology/speech#21]
How to add chinese option in tts-lang to let iCub speak in chinese?

**Comment by pattacini** [comment]
Hi @linzdg 

First, you have to build this repository with the CMake flag `BUILD_SVOX_SPEECH` enabled.

Then, you have to launch in a row:
- `yarpdev --device speech --lingware-context speech --default-language <lang-code> --pitch 80 --speed 110`
  where `lang-code` represents the code language as specified for example [here](https://support.twilio.com/hc/en-us/articles/223132827-What-Languages-can-the-Say-TwiML-Verb-Speak-). You ought to test it to check if Chinese is actually supported.
- `iSpeak --package speech-dev`

Make the following connections:
- `yarp connect /iSpeak/speech-dev/rpc /icub/speech:rpc`
- `yarp connect /iSpeak/emotions:o /icub/face/emotions/in`

Once done, you could issue the command below:
- `echo "Hi, I'm iCub" | yarp write ... /iSpeak`

Just play with the command-line options `pitch`, `speed` and fiddle with the words in the sentence in order to improve the final results.

Hope it helps.

**Comment by linzdg** [comment]
From the link, I know that Twilio's basic Alice voice uses an improved engine that is capable of speaking 26 total dialects including Chinese (zh-CN), but the svox-speech supported language does not cover Chinese. Where can I download the text analysis resource file and signal generation Lingware resource file about Chinese? Because I found there are such files in the /speech/svox-speech/tts-lang. There are only six languages(en-US, EN-GB, es-ES, fr-FR, it-IT, de-DE) are supported in svox-speech.

**Comment by pattacini** [comment]
Unfortunately, @linzdg I have no clue; I'm not very in the know of this matter. I'm a simple user who sometimes tries to keep the repo neat 😄 

Maybe @apaikan could give heads-up on this.

**Comment by apaikan** [comment]
hi Guys with special thanks to my master @pattacini :)

by the time when i was looking into svox tts, i remember i struggled to download the tts engine files... I found them somewhere in an Android/java code sample repo. I remember i found somewhere else also Portuguese tts for svox but couldn't manage to make it work. 
I guess one needs to understand how this old (obsoleted google android) engine work ;)

sorry that I couldn't help more .

**Comment by vtikha** [comment]
@linzdg unfortunately, as you correctly noted, svox (sox PICO) supports only (officially) 6 different lingware resources. We will have a look at the Twilio's engine that you mentioned.

@apaikan 🎉
