### ISSUE TITLE
Better quality speech synthesis

### ISSUE THREAD

**Issue by fvannu** [robotology/speech#23]
Dear all,

we would like to improve the audio quality of our iCub speech for both Italian and English.
At the moment we are using the Svox TTS generator, but I'm opening this issue, mainly to ask if any of you is using something else already.
For example, in this repository I saw some wrappers for Windows TTS and Acapela. Both seems better then the Svox. 
Is anybody using these? 
In case, do we need extra software (like SDK or else) to use them?
If you have any answer or use something other than these for speech synthesis, please let me know.

Thanks in advance for the help.

Best, 
Fabio

@reafrancesco

**Comment by pattacini** [comment]
Hi @fvannu 

We used in the past Acapela with better results in terms of sound quality and flexibility to tune the voice. Anyway, Acapela is proprietary software (licenses are quite expensive) that gets locked to a specific machine with a hardware key.

This turned out to be too much of a burden for us and, in the trade-off, svox has been performing just fine for our purposes.

Of course, trade-off remains very specific to the group.

**Comment by fvannu** [comment]
ok, I'll check Acapela or look for somethink different.

Thanks a lot for the help!
